[main]
outPath = "./configs/"
numFiles = 1
chain = true
transf = ["pitch"]
generateExpFolder = true
param_ext = '.txt'

[analysis]
window.len = 0.04
oversampling = 8

[pitch]
# Define pitch transposition window in seconds
window.len = 0.11
# Number of pitch transposition windows (so number of breakpoints - 1)
window.count = 3
# Unit for window length ('n' = number of windows)
window.unit = 'n'
# Standard deviation for random pitch transposition (in cents)
std = 90
# Truncation factor for the pitch transposition distribution
trunc = 1
# Type of breakpoint function (linear ramp)
BPFtype = 'ramp'
# Transition time for square BPF (in seconds)
trTime = 0.02